### ISSUE TITLE
Screen resolution issues

### ISSUE THREAD

**Issue by AlexisPradoLucero** [EdgarR13480/electron-flash-client#1]
I'm in this game, when it's in fullscreen, the bottom part isn't visible properly, but when I minimize it, the bottom part is visible. I would like the bottom part to be visible in fullscreen. The app is working great, but this is the only thing that needs fixing, especially when it's flash content in fullscreen.
![screenfull](https://github.com/EdgarR13480/electron-flash-client/assets/130103780/06e8c893-1390-4eaa-8161-3938a324ad03)
![minimized](https://github.com/EdgarR13480/electron-flash-client/assets/130103780/3ee57c5b-928d-48ca-98b9-e343d2a5df9c)

**Comment by EdgrSR** [comment]
Will be looking into that today! Thanks for the feedback

**Comment by EdgrSR** [comment]
@AlexisPradoLucero Should be fixed in the latest release

**Comment by AlexisPradoLucero** [comment]
Thank you very much now it looks good
![image](https://github.com/EdgarR13480/electron-flash-client/assets/130103780/03486b69-a9be-4eb7-a1de-421bcb1ce5e0)
